Use Mono.CSharp from GAC instead of NuGet package
Mono.CSharp from the GAC is more recent and allows the use of
tuples:

    var result = (1, "value");

Note that Mono.CSharp does not seem to support assignment to
variables:

    (int foo, int bar, string a) = (1, 2, "aa");

Fails with: error CS0584: Internal compiler error: CloneTo not
implemented for expression Mono.CSharp.TupleDeconstruct

Nor this tuple creation:

    (double, int) t1 = (4.5, 3);

Fails with: error CS1001: Unexpected symbol `,', expecting identifier

But it does support:

    (double Sum, int Count) t2 = (4.5, 3);